### ISSUE TITLE
Create components that are in the homepage

### ISSUE THREAD

**Issue by sanandnarayan** [Codebrahma/serverless-design-system#1]
- header
- footer
- hero
- icons

etc

we can adopt the atomic pattern that is followed in the current serverless codebase

i.e atoms, fragments, layouts, pages

for each components, create a documentation page (like button/testimonial). 
we can ignore creating storybooks for now

kindly create your components as thoughtfully as you can. following SRP , high cohesion, low coupling. 

take a look at 
http://jxnblk.com/writing/posts/defining-component-apis-in-react/

use styled components and styled system well

**Comment by Kameshwaran** [comment]
Merged the feature to master
