### ISSUE TITLE
Create a documentation infrastructure for design systems

### ISSUE THREAD

**Issue by sanandnarayan** [Codebrahma/serverless-design-system#4]
Create a sidebar which lists components categorized into two. Atoms and molecules.
The output needs to feel like this [one](https://pricelinelabs.github.io/design-system/Heading) + both the categories like this [one](https://auth0-cosmos.now.sh/docs/#/)

The current site is a static side made out of [x0](https://github.com/c8r/x0) with each file residing in docs/src/ rendering itself into a page . (i.e the routing in x0 is file system based. every file is a route). the template residies in docs/src/template.js and then every page renders itself.  LiveEdit is the react component (docs/src/LiveEdit.js) that renders the live editable documentation using react live. Lets switch to gatsby for this static site.

What you need to do is use React Router and show links in the sidebar. the links should be in two categories. Atoms and molecules. consisting of md files from atoms folder and molecules folder respectively.

1. It must be very easy for the developer to create docs. else they wont. 
2. Later we should extract the documentation infra into a npm module, so that we can npm install and it directly renders the md files inside docs/atoms and docs/molecules with the components themselves in src/ folder

Reference:
https://github.com/pricelinelabs/design-system
https://github.com/auth0/cosmos/tree/master/internal/docs
https://github.com/jxnblk/create-docs
https://github.com/jxnblk/superbox/blob/master/docs/index.md

**Comment by sanandnarayan** [comment]
Developers will create docs in the docs/atoms and docs/molecules folders (which you need to create now) 
you can mv the docs/src/button.js into docs/atoms and docs/src/testimonial.js into docs/molecules

**Comment by prasanna1211** [comment]
1. So I can expect every developer to fill in the ```.md``` file inside atoms and molecules folder ? (I think the answer is yes). Moving to ```gatsby.js``` is to pull out these docs and auto build ?

2. To build this gatsby site, we should still use the components in the ```src/``` to build it ? As per your idea I think we should create a separate set of components for Docs. (Ex: Sidebar, Navbar ...)

3. Preferred styling method for the Docs ? (SASS or styled components)

**Comment by sanandnarayan** [comment]
1a. Yes. 

1b. Moving to gatsby.js is because we want to use just one static site generator across our company and that is going to be gatsby

2. the components inside src/ are the components of the design system. This will ultimately be different for every project. in the current case the components inside src/ are the components of the serverless design system.  You can use docs/infra/components or whatever structure outside of src/ . Do remember that ultimately you want to extract them into npm module so that if you can create another design system we can reuse the infra created. What you are creating now is the documentation infrastructure for design systems

3. Styled components/styled system

**Comment by sanandnarayan** [comment]
With what you create a developer should be able to create documentation for his design system in one command. So he does something like create-doc and he gets a folder structure. where he drops his design system in src/ and starts creating docs in docs/atoms and docs/molecules. and he gets live editable demo of his design system

**Comment by sanandnarayan** [comment]
@prasanna1211 @Kameshwaran look at this 
https://www.docz.site/documentation/components-api

**Comment by sanandnarayan** [comment]
@prasanna1211 if you can create a navigation sidebar it should be good for now

**Comment by sanandnarayan** [comment]
https://github.com/pedronauck/docz
or 
https://github.com/jxnblk/mdx-docs
